server:
  port: 8090
  servlet:
    context-path: /ms-property-invoice

spring:
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: "jdbc:postgresql://localhost:5432/property"
    username: postgres
    password: postgres