version: '3.8'
services:
  property-invoice.db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_DB=property
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - ./create-table.sql:/docker-entrypoint-initdb.d/create-table.sql
volumes:
  db:
    driver: local